<?php

require_once('includes/Writer/FileWriterInterface.php');
require_once('includes/Settings/GlobalSettings.php');
require_once('includes/Database/DbHelper.php');

class VHostFileWriter implements FileWriterInterface {

  public function write() {
    $sites = $this->getSites();
    $this->addVhosts($sites);
  }

  private function getSites() {
    $db = DbHelper::getDatabase();

    $result = $db->query('SELECT * FROM sites');

    $sites = array();
    if ($result->num_rows > 0) {
      while ($site = $result->fetch_assoc()) {
        $sites[] = $site;
      }
    }

    return $sites;
  }

  private function addVhosts($sites){
    $settings = GlobalSettings::getInstance();

    $file = fopen($settings->get('path_to_vhosts_file'), 'w');

    if (!$file) {
      throw new Exception('Unable to write to the vhosts file.');
    }

    $lines_to_write = array();
    $lines_to_write[] = "# This file was generated by the Host Manager tool." . PHP_EOL;
    $lines_to_write[] = "# This file is replaced every so often so to persist any changes, please ensure you add it with the Host Manager tool." . PHP_EOL . PHP_EOL;

    $lines_to_write[] = "<VirtualHost *:80>" . PHP_EOL;
    $lines_to_write[] = "\tDocumentRoot \"/Applications/XAMPP/xamppfiles/htdocs/\"" . PHP_EOL;
    $lines_to_write[] = "\tServerName localhost" . PHP_EOL;
    $lines_to_write[] = "<VirtualHost *:80>" . PHP_EOL . PHP_EOL;

    foreach ($sites as $site) {
      $lines_to_write[] = "<VirtualHost *:80>" . PHP_EOL;
      $lines_to_write[] = sprintf("\tDocumentRoot \"%s\"" . PHP_EOL, $site['docroot']);
      $lines_to_write[] = "\tServerName local.cjogle.com" . PHP_EOL;
      $lines_to_write[] = "<VirtualHost *:80>" . PHP_EOL . PHP_EOL;
    }

    foreach ($lines_to_write as $line) {
      fwrite($file, $line);
    }

    fclose($file);
  }
}
